[project]
name = "arian-receipts"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
	"fastapi",
	"google-genai",
	"llama-cpp-python",
	"opencv-python-headless",
	"pytesseract",
	"python-multipart",
	"uvicorn[standard]",
  "huggingface_hub"
]

[tool.ruff.format]
indent-style = "tab"