# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from arian.v1 import category_services_pb2 as arian_dot_v1_dot_category__services__pb2


class CategoryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListCategories = channel.unary_unary(
                '/arian.v1.CategoryService/ListCategories',
                request_serializer=arian_dot_v1_dot_category__services__pb2.ListCategoriesRequest.SerializeToString,
                response_deserializer=arian_dot_v1_dot_category__services__pb2.ListCategoriesResponse.FromString,
                )
        self.ListCategoriesWithUsage = channel.unary_unary(
                '/arian.v1.CategoryService/ListCategoriesWithUsage',
                request_serializer=arian_dot_v1_dot_category__services__pb2.ListCategoriesWithUsageRequest.SerializeToString,
                response_deserializer=arian_dot_v1_dot_category__services__pb2.ListCategoriesWithUsageResponse.FromString,
                )
        self.ListCategoriesForUser = channel.unary_unary(
                '/arian.v1.CategoryService/ListCategoriesForUser',
                request_serializer=arian_dot_v1_dot_category__services__pb2.ListCategoriesForUserRequest.SerializeToString,
                response_deserializer=arian_dot_v1_dot_category__services__pb2.ListCategoriesForUserResponse.FromString,
                )
        self.GetCategory = channel.unary_unary(
                '/arian.v1.CategoryService/GetCategory',
                request_serializer=arian_dot_v1_dot_category__services__pb2.GetCategoryRequest.SerializeToString,
                response_deserializer=arian_dot_v1_dot_category__services__pb2.GetCategoryResponse.FromString,
                )
        self.GetCategoryBySlug = channel.unary_unary(
                '/arian.v1.CategoryService/GetCategoryBySlug',
                request_serializer=arian_dot_v1_dot_category__services__pb2.GetCategoryBySlugRequest.SerializeToString,
                response_deserializer=arian_dot_v1_dot_category__services__pb2.GetCategoryBySlugResponse.FromString,
                )
        self.GetCategoryWithStats = channel.unary_unary(
                '/arian.v1.CategoryService/GetCategoryWithStats',
                request_serializer=arian_dot_v1_dot_category__services__pb2.GetCategoryWithStatsRequest.SerializeToString,
                response_deserializer=arian_dot_v1_dot_category__services__pb2.GetCategoryWithStatsResponse.FromString,
                )
        self.CreateCategory = channel.unary_unary(
                '/arian.v1.CategoryService/CreateCategory',
                request_serializer=arian_dot_v1_dot_category__services__pb2.CreateCategoryRequest.SerializeToString,
                response_deserializer=arian_dot_v1_dot_category__services__pb2.CreateCategoryResponse.FromString,
                )
        self.BulkCreateCategories = channel.unary_unary(
                '/arian.v1.CategoryService/BulkCreateCategories',
                request_serializer=arian_dot_v1_dot_category__services__pb2.BulkCreateCategoriesRequest.SerializeToString,
                response_deserializer=arian_dot_v1_dot_category__services__pb2.BulkCreateCategoriesResponse.FromString,
                )
        self.UpdateCategory = channel.unary_unary(
                '/arian.v1.CategoryService/UpdateCategory',
                request_serializer=arian_dot_v1_dot_category__services__pb2.UpdateCategoryRequest.SerializeToString,
                response_deserializer=arian_dot_v1_dot_category__services__pb2.UpdateCategoryResponse.FromString,
                )
        self.DeleteCategory = channel.unary_unary(
                '/arian.v1.CategoryService/DeleteCategory',
                request_serializer=arian_dot_v1_dot_category__services__pb2.DeleteCategoryRequest.SerializeToString,
                response_deserializer=arian_dot_v1_dot_category__services__pb2.DeleteCategoryResponse.FromString,
                )
        self.DeleteUnusedCategories = channel.unary_unary(
                '/arian.v1.CategoryService/DeleteUnusedCategories',
                request_serializer=arian_dot_v1_dot_category__services__pb2.DeleteUnusedCategoriesRequest.SerializeToString,
                response_deserializer=arian_dot_v1_dot_category__services__pb2.DeleteUnusedCategoriesResponse.FromString,
                )
        self.GetCategoryUsageStats = channel.unary_unary(
                '/arian.v1.CategoryService/GetCategoryUsageStats',
                request_serializer=arian_dot_v1_dot_category__services__pb2.GetCategoryUsageStatsRequest.SerializeToString,
                response_deserializer=arian_dot_v1_dot_category__services__pb2.GetCategoryUsageStatsResponse.FromString,
                )
        self.GetCategoriesWithStats = channel.unary_unary(
                '/arian.v1.CategoryService/GetCategoriesWithStats',
                request_serializer=arian_dot_v1_dot_category__services__pb2.GetCategoriesWithStatsRequest.SerializeToString,
                response_deserializer=arian_dot_v1_dot_category__services__pb2.GetCategoriesWithStatsResponse.FromString,
                )
        self.SearchCategories = channel.unary_unary(
                '/arian.v1.CategoryService/SearchCategories',
                request_serializer=arian_dot_v1_dot_category__services__pb2.SearchCategoriesRequest.SerializeToString,
                response_deserializer=arian_dot_v1_dot_category__services__pb2.SearchCategoriesResponse.FromString,
                )
        self.ListCategorySlugs = channel.unary_unary(
                '/arian.v1.CategoryService/ListCategorySlugs',
                request_serializer=arian_dot_v1_dot_category__services__pb2.ListCategorySlugsRequest.SerializeToString,
                response_deserializer=arian_dot_v1_dot_category__services__pb2.ListCategorySlugsResponse.FromString,
                )
        self.GetMostUsedCategoriesForUser = channel.unary_unary(
                '/arian.v1.CategoryService/GetMostUsedCategoriesForUser',
                request_serializer=arian_dot_v1_dot_category__services__pb2.GetMostUsedCategoriesForUserRequest.SerializeToString,
                response_deserializer=arian_dot_v1_dot_category__services__pb2.GetMostUsedCategoriesForUserResponse.FromString,
                )
        self.GetUnusedCategories = channel.unary_unary(
                '/arian.v1.CategoryService/GetUnusedCategories',
                request_serializer=arian_dot_v1_dot_category__services__pb2.GetUnusedCategoriesRequest.SerializeToString,
                response_deserializer=arian_dot_v1_dot_category__services__pb2.GetUnusedCategoriesResponse.FromString,
                )


class CategoryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListCategories(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCategoriesWithUsage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCategoriesForUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCategory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCategoryBySlug(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCategoryWithStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateCategory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BulkCreateCategories(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateCategory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCategory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUnusedCategories(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCategoryUsageStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCategoriesWithStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchCategories(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCategorySlugs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMostUsedCategoriesForUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUnusedCategories(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CategoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListCategories': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCategories,
                    request_deserializer=arian_dot_v1_dot_category__services__pb2.ListCategoriesRequest.FromString,
                    response_serializer=arian_dot_v1_dot_category__services__pb2.ListCategoriesResponse.SerializeToString,
            ),
            'ListCategoriesWithUsage': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCategoriesWithUsage,
                    request_deserializer=arian_dot_v1_dot_category__services__pb2.ListCategoriesWithUsageRequest.FromString,
                    response_serializer=arian_dot_v1_dot_category__services__pb2.ListCategoriesWithUsageResponse.SerializeToString,
            ),
            'ListCategoriesForUser': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCategoriesForUser,
                    request_deserializer=arian_dot_v1_dot_category__services__pb2.ListCategoriesForUserRequest.FromString,
                    response_serializer=arian_dot_v1_dot_category__services__pb2.ListCategoriesForUserResponse.SerializeToString,
            ),
            'GetCategory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCategory,
                    request_deserializer=arian_dot_v1_dot_category__services__pb2.GetCategoryRequest.FromString,
                    response_serializer=arian_dot_v1_dot_category__services__pb2.GetCategoryResponse.SerializeToString,
            ),
            'GetCategoryBySlug': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCategoryBySlug,
                    request_deserializer=arian_dot_v1_dot_category__services__pb2.GetCategoryBySlugRequest.FromString,
                    response_serializer=arian_dot_v1_dot_category__services__pb2.GetCategoryBySlugResponse.SerializeToString,
            ),
            'GetCategoryWithStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCategoryWithStats,
                    request_deserializer=arian_dot_v1_dot_category__services__pb2.GetCategoryWithStatsRequest.FromString,
                    response_serializer=arian_dot_v1_dot_category__services__pb2.GetCategoryWithStatsResponse.SerializeToString,
            ),
            'CreateCategory': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCategory,
                    request_deserializer=arian_dot_v1_dot_category__services__pb2.CreateCategoryRequest.FromString,
                    response_serializer=arian_dot_v1_dot_category__services__pb2.CreateCategoryResponse.SerializeToString,
            ),
            'BulkCreateCategories': grpc.unary_unary_rpc_method_handler(
                    servicer.BulkCreateCategories,
                    request_deserializer=arian_dot_v1_dot_category__services__pb2.BulkCreateCategoriesRequest.FromString,
                    response_serializer=arian_dot_v1_dot_category__services__pb2.BulkCreateCategoriesResponse.SerializeToString,
            ),
            'UpdateCategory': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateCategory,
                    request_deserializer=arian_dot_v1_dot_category__services__pb2.UpdateCategoryRequest.FromString,
                    response_serializer=arian_dot_v1_dot_category__services__pb2.UpdateCategoryResponse.SerializeToString,
            ),
            'DeleteCategory': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCategory,
                    request_deserializer=arian_dot_v1_dot_category__services__pb2.DeleteCategoryRequest.FromString,
                    response_serializer=arian_dot_v1_dot_category__services__pb2.DeleteCategoryResponse.SerializeToString,
            ),
            'DeleteUnusedCategories': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUnusedCategories,
                    request_deserializer=arian_dot_v1_dot_category__services__pb2.DeleteUnusedCategoriesRequest.FromString,
                    response_serializer=arian_dot_v1_dot_category__services__pb2.DeleteUnusedCategoriesResponse.SerializeToString,
            ),
            'GetCategoryUsageStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCategoryUsageStats,
                    request_deserializer=arian_dot_v1_dot_category__services__pb2.GetCategoryUsageStatsRequest.FromString,
                    response_serializer=arian_dot_v1_dot_category__services__pb2.GetCategoryUsageStatsResponse.SerializeToString,
            ),
            'GetCategoriesWithStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCategoriesWithStats,
                    request_deserializer=arian_dot_v1_dot_category__services__pb2.GetCategoriesWithStatsRequest.FromString,
                    response_serializer=arian_dot_v1_dot_category__services__pb2.GetCategoriesWithStatsResponse.SerializeToString,
            ),
            'SearchCategories': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchCategories,
                    request_deserializer=arian_dot_v1_dot_category__services__pb2.SearchCategoriesRequest.FromString,
                    response_serializer=arian_dot_v1_dot_category__services__pb2.SearchCategoriesResponse.SerializeToString,
            ),
            'ListCategorySlugs': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCategorySlugs,
                    request_deserializer=arian_dot_v1_dot_category__services__pb2.ListCategorySlugsRequest.FromString,
                    response_serializer=arian_dot_v1_dot_category__services__pb2.ListCategorySlugsResponse.SerializeToString,
            ),
            'GetMostUsedCategoriesForUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMostUsedCategoriesForUser,
                    request_deserializer=arian_dot_v1_dot_category__services__pb2.GetMostUsedCategoriesForUserRequest.FromString,
                    response_serializer=arian_dot_v1_dot_category__services__pb2.GetMostUsedCategoriesForUserResponse.SerializeToString,
            ),
            'GetUnusedCategories': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUnusedCategories,
                    request_deserializer=arian_dot_v1_dot_category__services__pb2.GetUnusedCategoriesRequest.FromString,
                    response_serializer=arian_dot_v1_dot_category__services__pb2.GetUnusedCategoriesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'arian.v1.CategoryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CategoryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListCategories(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/arian.v1.CategoryService/ListCategories',
            arian_dot_v1_dot_category__services__pb2.ListCategoriesRequest.SerializeToString,
            arian_dot_v1_dot_category__services__pb2.ListCategoriesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListCategoriesWithUsage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/arian.v1.CategoryService/ListCategoriesWithUsage',
            arian_dot_v1_dot_category__services__pb2.ListCategoriesWithUsageRequest.SerializeToString,
            arian_dot_v1_dot_category__services__pb2.ListCategoriesWithUsageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListCategoriesForUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/arian.v1.CategoryService/ListCategoriesForUser',
            arian_dot_v1_dot_category__services__pb2.ListCategoriesForUserRequest.SerializeToString,
            arian_dot_v1_dot_category__services__pb2.ListCategoriesForUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCategory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/arian.v1.CategoryService/GetCategory',
            arian_dot_v1_dot_category__services__pb2.GetCategoryRequest.SerializeToString,
            arian_dot_v1_dot_category__services__pb2.GetCategoryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCategoryBySlug(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/arian.v1.CategoryService/GetCategoryBySlug',
            arian_dot_v1_dot_category__services__pb2.GetCategoryBySlugRequest.SerializeToString,
            arian_dot_v1_dot_category__services__pb2.GetCategoryBySlugResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCategoryWithStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/arian.v1.CategoryService/GetCategoryWithStats',
            arian_dot_v1_dot_category__services__pb2.GetCategoryWithStatsRequest.SerializeToString,
            arian_dot_v1_dot_category__services__pb2.GetCategoryWithStatsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateCategory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/arian.v1.CategoryService/CreateCategory',
            arian_dot_v1_dot_category__services__pb2.CreateCategoryRequest.SerializeToString,
            arian_dot_v1_dot_category__services__pb2.CreateCategoryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BulkCreateCategories(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/arian.v1.CategoryService/BulkCreateCategories',
            arian_dot_v1_dot_category__services__pb2.BulkCreateCategoriesRequest.SerializeToString,
            arian_dot_v1_dot_category__services__pb2.BulkCreateCategoriesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateCategory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/arian.v1.CategoryService/UpdateCategory',
            arian_dot_v1_dot_category__services__pb2.UpdateCategoryRequest.SerializeToString,
            arian_dot_v1_dot_category__services__pb2.UpdateCategoryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteCategory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/arian.v1.CategoryService/DeleteCategory',
            arian_dot_v1_dot_category__services__pb2.DeleteCategoryRequest.SerializeToString,
            arian_dot_v1_dot_category__services__pb2.DeleteCategoryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteUnusedCategories(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/arian.v1.CategoryService/DeleteUnusedCategories',
            arian_dot_v1_dot_category__services__pb2.DeleteUnusedCategoriesRequest.SerializeToString,
            arian_dot_v1_dot_category__services__pb2.DeleteUnusedCategoriesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCategoryUsageStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/arian.v1.CategoryService/GetCategoryUsageStats',
            arian_dot_v1_dot_category__services__pb2.GetCategoryUsageStatsRequest.SerializeToString,
            arian_dot_v1_dot_category__services__pb2.GetCategoryUsageStatsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCategoriesWithStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/arian.v1.CategoryService/GetCategoriesWithStats',
            arian_dot_v1_dot_category__services__pb2.GetCategoriesWithStatsRequest.SerializeToString,
            arian_dot_v1_dot_category__services__pb2.GetCategoriesWithStatsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SearchCategories(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/arian.v1.CategoryService/SearchCategories',
            arian_dot_v1_dot_category__services__pb2.SearchCategoriesRequest.SerializeToString,
            arian_dot_v1_dot_category__services__pb2.SearchCategoriesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListCategorySlugs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/arian.v1.CategoryService/ListCategorySlugs',
            arian_dot_v1_dot_category__services__pb2.ListCategorySlugsRequest.SerializeToString,
            arian_dot_v1_dot_category__services__pb2.ListCategorySlugsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMostUsedCategoriesForUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/arian.v1.CategoryService/GetMostUsedCategoriesForUser',
            arian_dot_v1_dot_category__services__pb2.GetMostUsedCategoriesForUserRequest.SerializeToString,
            arian_dot_v1_dot_category__services__pb2.GetMostUsedCategoriesForUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUnusedCategories(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/arian.v1.CategoryService/GetUnusedCategories',
            arian_dot_v1_dot_category__services__pb2.GetUnusedCategoriesRequest.SerializeToString,
            arian_dot_v1_dot_category__services__pb2.GetUnusedCategoriesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
