# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: arian/v1/dashboard.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.type import date_pb2 as google_dot_type_dot_date__pb2
from google.type import money_pb2 as google_dot_type_dot_money__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x61rian/v1/dashboard.proto\x12\x08\x61rian.v1\x1a\x16google/type/date.proto\x1a\x17google/type/money.proto\"\x8f\x01\n\nTrendPoint\x12%\n\x04\x64\x61te\x18\x01 \x01(\x0b\x32\x11.google.type.DateR\x04\x64\x61te\x12*\n\x06income\x18\x02 \x01(\x0b\x32\x12.google.type.MoneyR\x06income\x12.\n\x08\x65xpenses\x18\x03 \x01(\x0b\x32\x12.google.type.MoneyR\x08\x65xpenses\"\xab\x01\n\x11MonthlyComparison\x12\x14\n\x05month\x18\x01 \x01(\tR\x05month\x12*\n\x06income\x18\x02 \x01(\x0b\x32\x12.google.type.MoneyR\x06income\x12.\n\x08\x65xpenses\x18\x03 \x01(\x0b\x32\x12.google.type.MoneyR\x08\x65xpenses\x12$\n\x03net\x18\x04 \x01(\x0b\x32\x12.google.type.MoneyR\x03net\"\xd4\x02\n\x10\x44\x61shboardSummary\x12%\n\x0etotal_accounts\x18\x01 \x01(\x03R\rtotalAccounts\x12-\n\x12total_transactions\x18\x02 \x01(\x03R\x11totalTransactions\x12\x35\n\x0ctotal_income\x18\x03 \x01(\x0b\x32\x12.google.type.MoneyR\x0btotalIncome\x12\x39\n\x0etotal_expenses\x18\x04 \x01(\x0b\x32\x12.google.type.MoneyR\rtotalExpenses\x12\x39\n\x19transactions_last_30_days\x18\x05 \x01(\x03R\x16transactionsLast30Days\x12=\n\x1auncategorized_transactions\x18\x06 \x01(\x03R\x19uncategorizedTransactions\"\xb1\x01\n\x0bTopCategory\x12\x12\n\x04slug\x18\x01 \x01(\tR\x04slug\x12\x14\n\x05label\x18\x02 \x01(\tR\x05label\x12\x14\n\x05\x63olor\x18\x03 \x01(\tR\x05\x63olor\x12+\n\x11transaction_count\x18\x04 \x01(\x03R\x10transactionCount\x12\x35\n\x0ctotal_amount\x18\x05 \x01(\x0b\x32\x12.google.type.MoneyR\x0btotalAmount\"\xc0\x01\n\x0bTopMerchant\x12\x1a\n\x08merchant\x18\x01 \x01(\tR\x08merchant\x12+\n\x11transaction_count\x18\x02 \x01(\x03R\x10transactionCount\x12\x35\n\x0ctotal_amount\x18\x03 \x01(\x0b\x32\x12.google.type.MoneyR\x0btotalAmount\x12\x31\n\navg_amount\x18\x04 \x01(\x0b\x32\x12.google.type.MoneyR\tavgAmountB!Z\x1f\x61riand/gen/go/arian/v1;ariandv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'arian.v1.dashboard_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\037ariand/gen/go/arian/v1;ariandv1'
  _globals['_TRENDPOINT']._serialized_start=88
  _globals['_TRENDPOINT']._serialized_end=231
  _globals['_MONTHLYCOMPARISON']._serialized_start=234
  _globals['_MONTHLYCOMPARISON']._serialized_end=405
  _globals['_DASHBOARDSUMMARY']._serialized_start=408
  _globals['_DASHBOARDSUMMARY']._serialized_end=748
  _globals['_TOPCATEGORY']._serialized_start=751
  _globals['_TOPCATEGORY']._serialized_end=928
  _globals['_TOPMERCHANT']._serialized_start=931
  _globals['_TOPMERCHANT']._serialized_end=1123
# @@protoc_insertion_point(module_scope)
