# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: arian/v1/enums.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x61rian/v1/enums.proto\x12\x08\x61rian.v1*\x95\x01\n\x0b\x41\x63\x63ountType\x12\x17\n\x13\x41\x43\x43OUNT_UNSPECIFIED\x10\x00\x12\x14\n\x10\x41\x43\x43OUNT_CHEQUING\x10\x01\x12\x13\n\x0f\x41\x43\x43OUNT_SAVINGS\x10\x02\x12\x17\n\x13\x41\x43\x43OUNT_CREDIT_CARD\x10\x03\x12\x16\n\x12\x41\x43\x43OUNT_INVESTMENT\x10\x04\x12\x11\n\rACCOUNT_OTHER\x10\x05*a\n\x14TransactionDirection\x12\x19\n\x15\x44IRECTION_UNSPECIFIED\x10\x00\x12\x16\n\x12\x44IRECTION_INCOMING\x10\x01\x12\x16\n\x12\x44IRECTION_OUTGOING\x10\x02*\xa0\x01\n\x14\x43\x61tegorizationStatus\x12\x1e\n\x1a\x43\x41TEGORIZATION_UNSPECIFIED\x10\x00\x12\x17\n\x13\x43\x41TEGORIZATION_NONE\x10\x01\x12\x17\n\x13\x43\x41TEGORIZATION_AUTO\x10\x02\x12\x19\n\x15\x43\x41TEGORIZATION_MANUAL\x10\x03\x12\x1b\n\x17\x43\x41TEGORIZATION_VERIFIED\x10\x04*L\n\rReceiptEngine\x12\x16\n\x12\x45NGINE_UNSPECIFIED\x10\x00\x12\x11\n\rENGINE_GEMINI\x10\x01\x12\x10\n\x0c\x45NGINE_LOCAL\x10\x02*\x7f\n\x12ReceiptParseStatus\x12\x1c\n\x18PARSE_STATUS_UNSPECIFIED\x10\x00\x12\x18\n\x14PARSE_STATUS_PENDING\x10\x01\x12\x18\n\x14PARSE_STATUS_SUCCESS\x10\x02\x12\x17\n\x13PARSE_STATUS_FAILED\x10\x03*\x87\x01\n\x11ReceiptLinkStatus\x12\x1b\n\x17LINK_STATUS_UNSPECIFIED\x10\x00\x12\x18\n\x14LINK_STATUS_UNLINKED\x10\x01\x12\x17\n\x13LINK_STATUS_MATCHED\x10\x02\x12\"\n\x1eLINK_STATUS_NEEDS_VERIFICATION\x10\x03\x42!Z\x1f\x61riand/gen/go/arian/v1;ariandv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'arian.v1.enums_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\037ariand/gen/go/arian/v1;ariandv1'
  _globals['_ACCOUNTTYPE']._serialized_start=35
  _globals['_ACCOUNTTYPE']._serialized_end=184
  _globals['_TRANSACTIONDIRECTION']._serialized_start=186
  _globals['_TRANSACTIONDIRECTION']._serialized_end=283
  _globals['_CATEGORIZATIONSTATUS']._serialized_start=286
  _globals['_CATEGORIZATIONSTATUS']._serialized_end=446
  _globals['_RECEIPTENGINE']._serialized_start=448
  _globals['_RECEIPTENGINE']._serialized_end=524
  _globals['_RECEIPTPARSESTATUS']._serialized_start=526
  _globals['_RECEIPTPARSESTATUS']._serialized_end=653
  _globals['_RECEIPTLINKSTATUS']._serialized_start=656
  _globals['_RECEIPTLINKSTATUS']._serialized_end=791
# @@protoc_insertion_point(module_scope)
