# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from arian.v1 import receipt_services_pb2 as arian_dot_v1_dot_receipt__services__pb2


class ReceiptServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListReceipts = channel.unary_unary(
                '/arian.v1.ReceiptService/ListReceipts',
                request_serializer=arian_dot_v1_dot_receipt__services__pb2.ListReceiptsRequest.SerializeToString,
                response_deserializer=arian_dot_v1_dot_receipt__services__pb2.ListReceiptsResponse.FromString,
                )
        self.GetReceipt = channel.unary_unary(
                '/arian.v1.ReceiptService/GetReceipt',
                request_serializer=arian_dot_v1_dot_receipt__services__pb2.GetReceiptRequest.SerializeToString,
                response_deserializer=arian_dot_v1_dot_receipt__services__pb2.GetReceiptResponse.FromString,
                )
        self.CreateReceipt = channel.unary_unary(
                '/arian.v1.ReceiptService/CreateReceipt',
                request_serializer=arian_dot_v1_dot_receipt__services__pb2.CreateReceiptRequest.SerializeToString,
                response_deserializer=arian_dot_v1_dot_receipt__services__pb2.CreateReceiptResponse.FromString,
                )
        self.UploadReceipt = channel.unary_unary(
                '/arian.v1.ReceiptService/UploadReceipt',
                request_serializer=arian_dot_v1_dot_receipt__services__pb2.UploadReceiptRequest.SerializeToString,
                response_deserializer=arian_dot_v1_dot_receipt__services__pb2.UploadReceiptResponse.FromString,
                )
        self.UpdateReceipt = channel.unary_unary(
                '/arian.v1.ReceiptService/UpdateReceipt',
                request_serializer=arian_dot_v1_dot_receipt__services__pb2.UpdateReceiptRequest.SerializeToString,
                response_deserializer=arian_dot_v1_dot_receipt__services__pb2.UpdateReceiptResponse.FromString,
                )
        self.DeleteReceipt = channel.unary_unary(
                '/arian.v1.ReceiptService/DeleteReceipt',
                request_serializer=arian_dot_v1_dot_receipt__services__pb2.DeleteReceiptRequest.SerializeToString,
                response_deserializer=arian_dot_v1_dot_receipt__services__pb2.DeleteReceiptResponse.FromString,
                )
        self.ParseReceipt = channel.unary_unary(
                '/arian.v1.ReceiptService/ParseReceipt',
                request_serializer=arian_dot_v1_dot_receipt__services__pb2.ParseReceiptRequest.SerializeToString,
                response_deserializer=arian_dot_v1_dot_receipt__services__pb2.ParseReceiptResponse.FromString,
                )
        self.GetReceiptsByTransaction = channel.unary_unary(
                '/arian.v1.ReceiptService/GetReceiptsByTransaction',
                request_serializer=arian_dot_v1_dot_receipt__services__pb2.GetReceiptsByTransactionRequest.SerializeToString,
                response_deserializer=arian_dot_v1_dot_receipt__services__pb2.GetReceiptsByTransactionResponse.FromString,
                )
        self.SearchReceipts = channel.unary_unary(
                '/arian.v1.ReceiptService/SearchReceipts',
                request_serializer=arian_dot_v1_dot_receipt__services__pb2.SearchReceiptsRequest.SerializeToString,
                response_deserializer=arian_dot_v1_dot_receipt__services__pb2.SearchReceiptsResponse.FromString,
                )
        self.ListReceiptItems = channel.unary_unary(
                '/arian.v1.ReceiptService/ListReceiptItems',
                request_serializer=arian_dot_v1_dot_receipt__services__pb2.ListReceiptItemsRequest.SerializeToString,
                response_deserializer=arian_dot_v1_dot_receipt__services__pb2.ListReceiptItemsResponse.FromString,
                )
        self.GetReceiptItem = channel.unary_unary(
                '/arian.v1.ReceiptService/GetReceiptItem',
                request_serializer=arian_dot_v1_dot_receipt__services__pb2.GetReceiptItemRequest.SerializeToString,
                response_deserializer=arian_dot_v1_dot_receipt__services__pb2.GetReceiptItemResponse.FromString,
                )
        self.CreateReceiptItem = channel.unary_unary(
                '/arian.v1.ReceiptService/CreateReceiptItem',
                request_serializer=arian_dot_v1_dot_receipt__services__pb2.CreateReceiptItemRequest.SerializeToString,
                response_deserializer=arian_dot_v1_dot_receipt__services__pb2.CreateReceiptItemResponse.FromString,
                )
        self.UpdateReceiptItem = channel.unary_unary(
                '/arian.v1.ReceiptService/UpdateReceiptItem',
                request_serializer=arian_dot_v1_dot_receipt__services__pb2.UpdateReceiptItemRequest.SerializeToString,
                response_deserializer=arian_dot_v1_dot_receipt__services__pb2.UpdateReceiptItemResponse.FromString,
                )
        self.DeleteReceiptItem = channel.unary_unary(
                '/arian.v1.ReceiptService/DeleteReceiptItem',
                request_serializer=arian_dot_v1_dot_receipt__services__pb2.DeleteReceiptItemRequest.SerializeToString,
                response_deserializer=arian_dot_v1_dot_receipt__services__pb2.DeleteReceiptItemResponse.FromString,
                )
        self.BulkCreateReceiptItems = channel.unary_unary(
                '/arian.v1.ReceiptService/BulkCreateReceiptItems',
                request_serializer=arian_dot_v1_dot_receipt__services__pb2.BulkCreateReceiptItemsRequest.SerializeToString,
                response_deserializer=arian_dot_v1_dot_receipt__services__pb2.BulkCreateReceiptItemsResponse.FromString,
                )
        self.DeleteReceiptItemsByReceipt = channel.unary_unary(
                '/arian.v1.ReceiptService/DeleteReceiptItemsByReceipt',
                request_serializer=arian_dot_v1_dot_receipt__services__pb2.DeleteReceiptItemsByReceiptRequest.SerializeToString,
                response_deserializer=arian_dot_v1_dot_receipt__services__pb2.DeleteReceiptItemsByReceiptResponse.FromString,
                )
        self.GetUnlinkedReceipts = channel.unary_unary(
                '/arian.v1.ReceiptService/GetUnlinkedReceipts',
                request_serializer=arian_dot_v1_dot_receipt__services__pb2.GetUnlinkedReceiptsRequest.SerializeToString,
                response_deserializer=arian_dot_v1_dot_receipt__services__pb2.GetUnlinkedReceiptsResponse.FromString,
                )
        self.GetReceiptMatchCandidates = channel.unary_unary(
                '/arian.v1.ReceiptService/GetReceiptMatchCandidates',
                request_serializer=arian_dot_v1_dot_receipt__services__pb2.GetReceiptMatchCandidatesRequest.SerializeToString,
                response_deserializer=arian_dot_v1_dot_receipt__services__pb2.GetReceiptMatchCandidatesResponse.FromString,
                )


class ReceiptServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListReceipts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReceipt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateReceipt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadReceipt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateReceipt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteReceipt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ParseReceipt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReceiptsByTransaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchReceipts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListReceiptItems(self, request, context):
        """Receipt items management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReceiptItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateReceiptItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateReceiptItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteReceiptItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BulkCreateReceiptItems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteReceiptItemsByReceipt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUnlinkedReceipts(self, request, context):
        """Utility operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReceiptMatchCandidates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReceiptServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListReceipts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListReceipts,
                    request_deserializer=arian_dot_v1_dot_receipt__services__pb2.ListReceiptsRequest.FromString,
                    response_serializer=arian_dot_v1_dot_receipt__services__pb2.ListReceiptsResponse.SerializeToString,
            ),
            'GetReceipt': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReceipt,
                    request_deserializer=arian_dot_v1_dot_receipt__services__pb2.GetReceiptRequest.FromString,
                    response_serializer=arian_dot_v1_dot_receipt__services__pb2.GetReceiptResponse.SerializeToString,
            ),
            'CreateReceipt': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateReceipt,
                    request_deserializer=arian_dot_v1_dot_receipt__services__pb2.CreateReceiptRequest.FromString,
                    response_serializer=arian_dot_v1_dot_receipt__services__pb2.CreateReceiptResponse.SerializeToString,
            ),
            'UploadReceipt': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadReceipt,
                    request_deserializer=arian_dot_v1_dot_receipt__services__pb2.UploadReceiptRequest.FromString,
                    response_serializer=arian_dot_v1_dot_receipt__services__pb2.UploadReceiptResponse.SerializeToString,
            ),
            'UpdateReceipt': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateReceipt,
                    request_deserializer=arian_dot_v1_dot_receipt__services__pb2.UpdateReceiptRequest.FromString,
                    response_serializer=arian_dot_v1_dot_receipt__services__pb2.UpdateReceiptResponse.SerializeToString,
            ),
            'DeleteReceipt': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteReceipt,
                    request_deserializer=arian_dot_v1_dot_receipt__services__pb2.DeleteReceiptRequest.FromString,
                    response_serializer=arian_dot_v1_dot_receipt__services__pb2.DeleteReceiptResponse.SerializeToString,
            ),
            'ParseReceipt': grpc.unary_unary_rpc_method_handler(
                    servicer.ParseReceipt,
                    request_deserializer=arian_dot_v1_dot_receipt__services__pb2.ParseReceiptRequest.FromString,
                    response_serializer=arian_dot_v1_dot_receipt__services__pb2.ParseReceiptResponse.SerializeToString,
            ),
            'GetReceiptsByTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReceiptsByTransaction,
                    request_deserializer=arian_dot_v1_dot_receipt__services__pb2.GetReceiptsByTransactionRequest.FromString,
                    response_serializer=arian_dot_v1_dot_receipt__services__pb2.GetReceiptsByTransactionResponse.SerializeToString,
            ),
            'SearchReceipts': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchReceipts,
                    request_deserializer=arian_dot_v1_dot_receipt__services__pb2.SearchReceiptsRequest.FromString,
                    response_serializer=arian_dot_v1_dot_receipt__services__pb2.SearchReceiptsResponse.SerializeToString,
            ),
            'ListReceiptItems': grpc.unary_unary_rpc_method_handler(
                    servicer.ListReceiptItems,
                    request_deserializer=arian_dot_v1_dot_receipt__services__pb2.ListReceiptItemsRequest.FromString,
                    response_serializer=arian_dot_v1_dot_receipt__services__pb2.ListReceiptItemsResponse.SerializeToString,
            ),
            'GetReceiptItem': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReceiptItem,
                    request_deserializer=arian_dot_v1_dot_receipt__services__pb2.GetReceiptItemRequest.FromString,
                    response_serializer=arian_dot_v1_dot_receipt__services__pb2.GetReceiptItemResponse.SerializeToString,
            ),
            'CreateReceiptItem': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateReceiptItem,
                    request_deserializer=arian_dot_v1_dot_receipt__services__pb2.CreateReceiptItemRequest.FromString,
                    response_serializer=arian_dot_v1_dot_receipt__services__pb2.CreateReceiptItemResponse.SerializeToString,
            ),
            'UpdateReceiptItem': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateReceiptItem,
                    request_deserializer=arian_dot_v1_dot_receipt__services__pb2.UpdateReceiptItemRequest.FromString,
                    response_serializer=arian_dot_v1_dot_receipt__services__pb2.UpdateReceiptItemResponse.SerializeToString,
            ),
            'DeleteReceiptItem': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteReceiptItem,
                    request_deserializer=arian_dot_v1_dot_receipt__services__pb2.DeleteReceiptItemRequest.FromString,
                    response_serializer=arian_dot_v1_dot_receipt__services__pb2.DeleteReceiptItemResponse.SerializeToString,
            ),
            'BulkCreateReceiptItems': grpc.unary_unary_rpc_method_handler(
                    servicer.BulkCreateReceiptItems,
                    request_deserializer=arian_dot_v1_dot_receipt__services__pb2.BulkCreateReceiptItemsRequest.FromString,
                    response_serializer=arian_dot_v1_dot_receipt__services__pb2.BulkCreateReceiptItemsResponse.SerializeToString,
            ),
            'DeleteReceiptItemsByReceipt': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteReceiptItemsByReceipt,
                    request_deserializer=arian_dot_v1_dot_receipt__services__pb2.DeleteReceiptItemsByReceiptRequest.FromString,
                    response_serializer=arian_dot_v1_dot_receipt__services__pb2.DeleteReceiptItemsByReceiptResponse.SerializeToString,
            ),
            'GetUnlinkedReceipts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUnlinkedReceipts,
                    request_deserializer=arian_dot_v1_dot_receipt__services__pb2.GetUnlinkedReceiptsRequest.FromString,
                    response_serializer=arian_dot_v1_dot_receipt__services__pb2.GetUnlinkedReceiptsResponse.SerializeToString,
            ),
            'GetReceiptMatchCandidates': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReceiptMatchCandidates,
                    request_deserializer=arian_dot_v1_dot_receipt__services__pb2.GetReceiptMatchCandidatesRequest.FromString,
                    response_serializer=arian_dot_v1_dot_receipt__services__pb2.GetReceiptMatchCandidatesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'arian.v1.ReceiptService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ReceiptService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListReceipts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/arian.v1.ReceiptService/ListReceipts',
            arian_dot_v1_dot_receipt__services__pb2.ListReceiptsRequest.SerializeToString,
            arian_dot_v1_dot_receipt__services__pb2.ListReceiptsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetReceipt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/arian.v1.ReceiptService/GetReceipt',
            arian_dot_v1_dot_receipt__services__pb2.GetReceiptRequest.SerializeToString,
            arian_dot_v1_dot_receipt__services__pb2.GetReceiptResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateReceipt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/arian.v1.ReceiptService/CreateReceipt',
            arian_dot_v1_dot_receipt__services__pb2.CreateReceiptRequest.SerializeToString,
            arian_dot_v1_dot_receipt__services__pb2.CreateReceiptResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UploadReceipt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/arian.v1.ReceiptService/UploadReceipt',
            arian_dot_v1_dot_receipt__services__pb2.UploadReceiptRequest.SerializeToString,
            arian_dot_v1_dot_receipt__services__pb2.UploadReceiptResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateReceipt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/arian.v1.ReceiptService/UpdateReceipt',
            arian_dot_v1_dot_receipt__services__pb2.UpdateReceiptRequest.SerializeToString,
            arian_dot_v1_dot_receipt__services__pb2.UpdateReceiptResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteReceipt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/arian.v1.ReceiptService/DeleteReceipt',
            arian_dot_v1_dot_receipt__services__pb2.DeleteReceiptRequest.SerializeToString,
            arian_dot_v1_dot_receipt__services__pb2.DeleteReceiptResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ParseReceipt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/arian.v1.ReceiptService/ParseReceipt',
            arian_dot_v1_dot_receipt__services__pb2.ParseReceiptRequest.SerializeToString,
            arian_dot_v1_dot_receipt__services__pb2.ParseReceiptResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetReceiptsByTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/arian.v1.ReceiptService/GetReceiptsByTransaction',
            arian_dot_v1_dot_receipt__services__pb2.GetReceiptsByTransactionRequest.SerializeToString,
            arian_dot_v1_dot_receipt__services__pb2.GetReceiptsByTransactionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SearchReceipts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/arian.v1.ReceiptService/SearchReceipts',
            arian_dot_v1_dot_receipt__services__pb2.SearchReceiptsRequest.SerializeToString,
            arian_dot_v1_dot_receipt__services__pb2.SearchReceiptsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListReceiptItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/arian.v1.ReceiptService/ListReceiptItems',
            arian_dot_v1_dot_receipt__services__pb2.ListReceiptItemsRequest.SerializeToString,
            arian_dot_v1_dot_receipt__services__pb2.ListReceiptItemsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetReceiptItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/arian.v1.ReceiptService/GetReceiptItem',
            arian_dot_v1_dot_receipt__services__pb2.GetReceiptItemRequest.SerializeToString,
            arian_dot_v1_dot_receipt__services__pb2.GetReceiptItemResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateReceiptItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/arian.v1.ReceiptService/CreateReceiptItem',
            arian_dot_v1_dot_receipt__services__pb2.CreateReceiptItemRequest.SerializeToString,
            arian_dot_v1_dot_receipt__services__pb2.CreateReceiptItemResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateReceiptItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/arian.v1.ReceiptService/UpdateReceiptItem',
            arian_dot_v1_dot_receipt__services__pb2.UpdateReceiptItemRequest.SerializeToString,
            arian_dot_v1_dot_receipt__services__pb2.UpdateReceiptItemResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteReceiptItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/arian.v1.ReceiptService/DeleteReceiptItem',
            arian_dot_v1_dot_receipt__services__pb2.DeleteReceiptItemRequest.SerializeToString,
            arian_dot_v1_dot_receipt__services__pb2.DeleteReceiptItemResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BulkCreateReceiptItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/arian.v1.ReceiptService/BulkCreateReceiptItems',
            arian_dot_v1_dot_receipt__services__pb2.BulkCreateReceiptItemsRequest.SerializeToString,
            arian_dot_v1_dot_receipt__services__pb2.BulkCreateReceiptItemsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteReceiptItemsByReceipt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/arian.v1.ReceiptService/DeleteReceiptItemsByReceipt',
            arian_dot_v1_dot_receipt__services__pb2.DeleteReceiptItemsByReceiptRequest.SerializeToString,
            arian_dot_v1_dot_receipt__services__pb2.DeleteReceiptItemsByReceiptResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUnlinkedReceipts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/arian.v1.ReceiptService/GetUnlinkedReceipts',
            arian_dot_v1_dot_receipt__services__pb2.GetUnlinkedReceiptsRequest.SerializeToString,
            arian_dot_v1_dot_receipt__services__pb2.GetUnlinkedReceiptsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetReceiptMatchCandidates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/arian.v1.ReceiptService/GetReceiptMatchCandidates',
            arian_dot_v1_dot_receipt__services__pb2.GetReceiptMatchCandidatesRequest.SerializeToString,
            arian_dot_v1_dot_receipt__services__pb2.GetReceiptMatchCandidatesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
