# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from arian.v1 import receipt_parsing_pb2 as arian_dot_v1_dot_receipt__parsing__pb2


class ReceiptParsingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ParseImage = channel.unary_unary(
                '/arian.v1.ReceiptParsingService/ParseImage',
                request_serializer=arian_dot_v1_dot_receipt__parsing__pb2.ParseImageRequest.SerializeToString,
                response_deserializer=arian_dot_v1_dot_receipt__parsing__pb2.ParseImageResponse.FromString,
                )
        self.GetStatus = channel.unary_unary(
                '/arian.v1.ReceiptParsingService/GetStatus',
                request_serializer=arian_dot_v1_dot_receipt__parsing__pb2.GetStatusRequest.SerializeToString,
                response_deserializer=arian_dot_v1_dot_receipt__parsing__pb2.GetStatusResponse.FromString,
                )


class ReceiptParsingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ParseImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReceiptParsingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ParseImage': grpc.unary_unary_rpc_method_handler(
                    servicer.ParseImage,
                    request_deserializer=arian_dot_v1_dot_receipt__parsing__pb2.ParseImageRequest.FromString,
                    response_serializer=arian_dot_v1_dot_receipt__parsing__pb2.ParseImageResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=arian_dot_v1_dot_receipt__parsing__pb2.GetStatusRequest.FromString,
                    response_serializer=arian_dot_v1_dot_receipt__parsing__pb2.GetStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'arian.v1.ReceiptParsingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ReceiptParsingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ParseImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/arian.v1.ReceiptParsingService/ParseImage',
            arian_dot_v1_dot_receipt__parsing__pb2.ParseImageRequest.SerializeToString,
            arian_dot_v1_dot_receipt__parsing__pb2.ParseImageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/arian.v1.ReceiptParsingService/GetStatus',
            arian_dot_v1_dot_receipt__parsing__pb2.GetStatusRequest.SerializeToString,
            arian_dot_v1_dot_receipt__parsing__pb2.GetStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
