# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: arian/v1/receipt_parsing.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x61rian/v1/receipt_parsing.proto\x12\x08\x61rian.v1\x1a\x17\x61rian/v1/receipts.proto\x1a\x14\x61rian/v1/enums.proto\"\x96\x01\n\x11ParseImageRequest\x12\x1d\n\nimage_data\x18\x01 \x01(\x0cR\timageData\x12!\n\x0c\x63ontent_type\x18\x02 \x01(\tR\x0b\x63ontentType\x12\x34\n\x06\x65ngine\x18\x03 \x01(\x0e\x32\x17.arian.v1.ReceiptEngineH\x00R\x06\x65ngine\x88\x01\x01\x42\t\n\x07_engine\"A\n\x12ParseImageResponse\x12+\n\x07receipt\x18\x01 \x01(\x0b\x32\x11.arian.v1.ReceiptR\x07receipt\"\x12\n\x10GetStatusRequest\"t\n\x11GetStatusResponse\x12\x36\n\tproviders\x18\x01 \x03(\x0b\x32\x18.arian.v1.ProviderStatusR\tproviders\x12\'\n\x0fservice_version\x18\x02 \x01(\tR\x0eserviceVersion\"\xa3\x01\n\x0eProviderStatus\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n\x04kind\x18\x02 \x01(\tR\x04kind\x12\x1c\n\tavailable\x18\x03 \x01(\x08R\tavailable\x12\x1b\n\x06reason\x18\x04 \x01(\tH\x00R\x06reason\x88\x01\x01\x12\x19\n\x05model\x18\x05 \x01(\tH\x01R\x05model\x88\x01\x01\x42\t\n\x07_reasonB\x08\n\x06_model2\xa6\x01\n\x15ReceiptParsingService\x12G\n\nParseImage\x12\x1b.arian.v1.ParseImageRequest\x1a\x1c.arian.v1.ParseImageResponse\x12\x44\n\tGetStatus\x12\x1a.arian.v1.GetStatusRequest\x1a\x1b.arian.v1.GetStatusResponseB!Z\x1f\x61riand/gen/go/arian/v1;ariandv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'arian.v1.receipt_parsing_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\037ariand/gen/go/arian/v1;ariandv1'
  _globals['_PARSEIMAGEREQUEST']._serialized_start=92
  _globals['_PARSEIMAGEREQUEST']._serialized_end=242
  _globals['_PARSEIMAGERESPONSE']._serialized_start=244
  _globals['_PARSEIMAGERESPONSE']._serialized_end=309
  _globals['_GETSTATUSREQUEST']._serialized_start=311
  _globals['_GETSTATUSREQUEST']._serialized_end=329
  _globals['_GETSTATUSRESPONSE']._serialized_start=331
  _globals['_GETSTATUSRESPONSE']._serialized_end=447
  _globals['_PROVIDERSTATUS']._serialized_start=450
  _globals['_PROVIDERSTATUS']._serialized_end=613
  _globals['_RECEIPTPARSINGSERVICE']._serialized_start=616
  _globals['_RECEIPTPARSINGSERVICE']._serialized_end=782
# @@protoc_insertion_point(module_scope)
