name: build and push container to GHCR

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  workflow_dispatch:

env:
  IMAGE_NAME: arian-receipts
  REGISTRY: ghcr.io
  PYTHON_VERSION: "3.11"

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: install uv
        uses: astral-sh/setup-uv@v3

      - name: run tests (if any exist)
        run: |
          if [ -d "tests" ] || grep -q "pytest\|unittest" pyproject.toml; then
            uv sync --dev
            uv run python -m pytest --version && uv run python -m pytest || echo "No tests found"
          else
            echo "No test directory or test framework found, skipping tests"
          fi

      - name: log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: get version info
        id: version
        run: |
          VERSION=$(grep '^version = ' pyproject.toml | cut -d'"' -f2)
          echo "version=v${VERSION}" >> $GITHUB_OUTPUT
          echo "build_time=$(date -u '+%Y-%m-%d_%H:%M:%S')" >> $GITHUB_OUTPUT
          echo "git_commit=${GITHUB_SHA}" >> $GITHUB_OUTPUT
          echo "git_branch=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
          echo "Version: v${VERSION}"

      - name: extract docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref_name == github.event.repository.default_branch }}
            type=raw,value=${{ steps.version.outputs.version }}
            type=sha
            type=ref,event=tag

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: build and push docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            VERSION=${{ steps.version.outputs.version }}
            BUILD_TIME=${{ steps.version.outputs.build_time }}
            GIT_COMMIT=${{ steps.version.outputs.git_commit }}
            GIT_BRANCH=${{ steps.version.outputs.git_branch }}
          cache-from: type=gha
          cache-to: type=gha,mode=max